name = "FilesystemDatastructures"
uuid = "89f0c457-83d8-4998-bfff-8b4a338c9833"
authors = ["Elliot Saba <staticfloat@gmail.com>"]
version = "1.0.0"

[compat]
julia = "1.5"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
